### ISSUE TITLE
ipad android

### ISSUE THREAD

**Issue by joett** [kartverket/example-clients#2]
Jeg har tat utgangspunkt i
"https://github.com/kartverket/example-clients/tree/master/leaflet"
Jeg ønsker også å legge til flyfotolag, hvordan gjør jeg det?

**Comment by carsmie** [comment]
Finn fram info om laget du øsnker å legge til på https://www.geonorge.no/ og så leser du dokumentasjon om leaflet  på http://leaflet.org/ hvordan man legger til et lag.
